[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "4dpLauJAPn95936DAYxcXTs6WNQ2EMCr4XFkitxuN5NX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/sasangaedirisinghe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "yarn run mocha -t 1000000 tests/"
